# Site settings
title: Martí Cuquet
email: nilvar@sindominio.net
baseurl: "/~nilvar" # the subpath of your site, e.g. /blog/
assetsurl: "/~nilvar/assets/"
imagesurl: "/~nilvar/images/"
url: "https://sindominio.net" # the base hostname & protocol for your site

# Jekyll settings
gems:
  - jekyll-pandoc

# Build settings
#markdown: kramdown
markdown: pandoc

# Pandoc options (see https://github.com/mfenner/jekyll-pandoc)
pandoc:
  extensions:
    - smart
